# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CodeGenAndTransformerApi
  # format_transformer.
  class FormatTransformer
    FORMAT_TRANSFORMER = [
      # TODO: Write general description for APIMATIC
      APIMATIC = 'apimatic'.freeze,

      # TODO: Write general description for WADL2009
      WADL2009 = 'wadl2009'.freeze,

      # TODO: Write general description for SWAGGER10
      SWAGGER10 = 'swagger10'.freeze,

      # TODO: Write general description for SWAGGER20
      SWAGGER20 = 'swagger20'.freeze,

      # TODO: Write general description for SWAGGERYAML
      SWAGGERYAML = 'swaggeryaml'.freeze,

      # TODO: Write general description for APIBLUEPRINT
      APIBLUEPRINT = 'apiblueprint'.freeze,

      # TODO: Write general description for RAML
      RAML = 'raml'.freeze
    ].freeze
  end
end
