# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CodeGenAndTransformerApi
  # format.
  class Format
    FORMAT = [
      # TODO: Write general description for ENUM_API_BLUEPRINT
      ENUM_API_BLUEPRINT = 'API Blueprint'.freeze,

      # TODO: Write general description for ENUM_GOOGLE_DISCOVERY
      ENUM_GOOGLE_DISCOVERY = 'Google Discovery'.freeze,

      # TODO: Write general description for RAML
      RAML = 'RAML'.freeze,

      # TODO: Write general description for WADL
      WADL = 'WADL'.freeze,

      # TODO: Write general description for SWAGGER
      SWAGGER = 'Swagger'.freeze,

      # TODO: Write general description for ENUM_IO_DOCS
      ENUM_IO_DOCS = 'IO Docs'.freeze,

      # TODO: Write general description for APIMATIC
      APIMATIC = 'APIMATIC'.freeze,

      # TODO: Write general description for WSDL
      WSDL = 'WSDL'.freeze,

      # TODO: Write general description for MASHAPE
      MASHAPE = 'Mashape'.freeze,

      # TODO: Write general description for POSTMAN
      POSTMAN = 'Postman'.freeze,

      # TODO: Write general description for HAR
      HAR = 'HAR'.freeze,

      # TODO: Write general description for OPEN_API_SPEC_300_RC1
      OPEN_API_SPEC_300_RC1 = 'OpenApi3'.freeze
    ].freeze
  end
end
