# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CodeGenAndTransformerApi
  # template.
  class Template
    TEMPLATE = [
      # TODO: Write general description for CS_PORTABLE_NET_LIB
      CS_PORTABLE_NET_LIB = 'cs_portable_net_lib'.freeze,

      # TODO: Write general description for JAVA_ECLIPSE_JRE_LIB
      JAVA_ECLIPSE_JRE_LIB = 'java_eclipse_jre_lib'.freeze,

      # TODO: Write general description for JAVA_GRADLE_ANDROID_LIB
      JAVA_GRADLE_ANDROID_LIB = 'java_gradle_android_lib'.freeze,

      # TODO: Write general description for OBJC_COCOA_TOUCH_IOS_LIB
      OBJC_COCOA_TOUCH_IOS_LIB = 'objc_cocoa_touch_ios_lib'.freeze,

      # TODO: Write general description for ANGULAR_JAVASCRIPT_LIB
      ANGULAR_JAVASCRIPT_LIB = 'angular_javascript_lib'.freeze,

      # TODO: Write general description for RUBY_GENERIC_LIB
      RUBY_GENERIC_LIB = 'ruby_generic_lib'.freeze,

      # TODO: Write general description for ENUM_PYTHON_GENERIC_LIB
      ENUM_PYTHON_GENERIC_LIB = 'python_generic_lib'.freeze,

      # TODO: Write general description for ENUM_PHP_GENERIC_LIB
      ENUM_PHP_GENERIC_LIB = 'php_generic_lib'.freeze,

      # TODO: Write general description for ENUM_NODE_JAVASCRIPT_LIB
      ENUM_NODE_JAVASCRIPT_LIB = 'node_javascript_lib'.freeze,

      # TODO: Write general description for ENUM_GO_GENERIC_LIB
      ENUM_GO_GENERIC_LIB = 'go_generic_lib'.freeze
    ].freeze
  end
end
