# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CodeGenAndTransformerApi
  # ValidateAnAPIDescriptionResponse Model.
  class ValidateAnAPIDescriptionResponse < BaseModel
    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :errors

    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :warnings

    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :messages

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :success

    # A mapping from model property names to API property names.
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash['errors'] = 'Errors'
        @_hash['warnings'] = 'Warnings'
        @_hash['messages'] = 'Messages'
        @_hash['success'] = 'Success'
      end
      @_hash
    end

    def initialize(errors = nil,
                   warnings = nil,
                   messages = nil,
                   success = nil)
      @errors = errors
      @warnings = warnings
      @messages = messages
      @success = success
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      errors = hash['Errors']
      warnings = hash['Warnings']
      messages = hash['Messages']
      success = hash['Success']

      # Create object from extracted values.
      ValidateAnAPIDescriptionResponse.new(errors,
                                           warnings,
                                           messages,
                                           success)
    end
  end
end
