<?php
/*
 * CodeGenAndTransformerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace CodeGenAndTransformerAPILib\Exceptions;

use CodeGenAndTransformerAPILib\APIException;
use CodeGenAndTransformerAPILib\APIHelper;

/**
 * @todo Write general description for this model
 */
class ValidationResultException extends APIException
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps Success
     * @var bool $success public property
     */
    public $success;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Errors
     * @var \CodeGenAndTransformerAPILib\Models\Message[] $errors public property
     */
    public $errors;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Warnings
     * @var \CodeGenAndTransformerAPILib\Models\Message[] $warnings public property
     */
    public $warnings;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Messages
     * @var \CodeGenAndTransformerAPILib\Models\Message[] $messages public property
     */
    public $messages;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false, false);
    }
}
