<?php
/*
 * CodeGenAndTransformerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace CodeGenAndTransformerAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class Format
{
    /**
     * TODO: Write general description for this element
     */
    const ENUM_API_BLUEPRINT = "API Blueprint";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_GOOGLE_DISCOVERY = "Google Discovery";

    /**
     * TODO: Write general description for this element
     */
    const RAML = "RAML";

    /**
     * TODO: Write general description for this element
     */
    const WADL = "WADL";

    /**
     * TODO: Write general description for this element
     */
    const SWAGGER = "Swagger";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_IO_DOCS = "IO Docs";

    /**
     * TODO: Write general description for this element
     */
    const APIMATIC = "APIMATIC";

    /**
     * TODO: Write general description for this element
     */
    const WSDL = "WSDL";

    /**
     * TODO: Write general description for this element
     */
    const MASHAPE = "Mashape";

    /**
     * TODO: Write general description for this element
     */
    const POSTMAN = "Postman";

    /**
     * TODO: Write general description for this element
     */
    const HAR = "HAR";

    /**
     * TODO: Write general description for this element
     */
    const OPEN_API_SPEC_300_RC1 = "OpenApi3";
}
