<?php
/*
 * CodeGenAndTransformerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace CodeGenAndTransformerAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class FormatTransformer
{
    /**
     * TODO: Write general description for this element
     */
    const APIMATIC = "apimatic";

    /**
     * TODO: Write general description for this element
     */
    const WADL2009 = "wadl2009";

    /**
     * TODO: Write general description for this element
     */
    const SWAGGER10 = "swagger10";

    /**
     * TODO: Write general description for this element
     */
    const SWAGGER20 = "swagger20";

    /**
     * TODO: Write general description for this element
     */
    const SWAGGERYAML = "swaggeryaml";

    /**
     * TODO: Write general description for this element
     */
    const APIBLUEPRINT = "apiblueprint";

    /**
     * TODO: Write general description for this element
     */
    const RAML = "raml";
}
