<?php
/*
 * CodeGenAndTransformerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace CodeGenAndTransformerAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ValidateAnAPIDescriptionResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps Errors
     * @var array $errors public property
     */
    public $errors;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Warnings
     * @var array $warnings public property
     */
    public $warnings;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Messages
     * @var array $messages public property
     */
    public $messages;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Success
     * @var bool $success public property
     */
    public $success;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $errors   Initialization value for $this->errors
     * @param array $warnings Initialization value for $this->warnings
     * @param array $messages Initialization value for $this->messages
     * @param bool  $success  Initialization value for $this->success
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->errors   = func_get_arg(0);
            $this->warnings = func_get_arg(1);
            $this->messages = func_get_arg(2);
            $this->success  = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Errors']   = $this->errors;
        $json['Warnings'] = $this->warnings;
        $json['Messages'] = $this->messages;
        $json['Success']  = $this->success;

        return $json;
    }
}
