# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CodeGenAndTransformerApi
  #  code_gen_and_transformer_api client class.
  class CodeGenAndTransformerApiClient
    # Singleton access to code_generation controller.
    # @return [CodeGenerationController] Returns the controller instance.
    def code_generation
      CodeGenerationController.instance
    end

    # Singleton access to api_description_validation controller.
    # @return [APIDescriptionValidationController] Returns the controller instance.
    def api_description_validation
      APIDescriptionValidationController.instance
    end

    # Singleton access to api_transformer controller.
    # @return [APITransformerController] Returns the controller instance.
    def api_transformer
      APITransformerController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end

    # Initializer with authentication and configuration parameters.
    def initialize(basic_auth_user_name: nil, basic_auth_password: nil)
      Configuration.basic_auth_user_name = basic_auth_user_name if
        basic_auth_user_name
      Configuration.basic_auth_password = basic_auth_password if
        basic_auth_password
    end
  end
end
